screen -S server10 -X quit
screen -S server9 -X quit
screen -S server8 -X quit
screen -S server7 -X quit
screen -S server6 -X quit
screen -S server5 -X quit
screen -S server4 -X quit
screen -S server3 -X quit
screen -S server2 -X quit
screen -S server1 -X quit
